app_login:
  path: /{locale}/login
  controller: App\Controller\Security\LoginController::login
  methods: [GET, POST]

app_register:
  path: /{locale}/register
  controller: App\Controller\Security\RegistrationController::registration
  methods: [GET, POST]

app_logout:
  path: /{locale}/logout
  methods: [GET]

ask_reset_password:
  path: /{locale}/reset-password
  controller: App\Controller\Security\AskResetPasswordController:askResetPassword
  methods: [GET, POST]

reset_password:
  path: /{locale}/reset-password/{passwordToken}
  controller: App\Controller\Security\ResetPasswordController:resetPassword
  methods: [GET, POST]

app_first_login:
  path: /{locale}/first-login
  controller: App\Controller\Security\FirstLoginController::firstLogin
  methods: [GET, POST]


# -------------------- User  -------------------------------------------------------------------------------------------
api_user:
  path: api/v1/{locale}/me
  controller: App\Controller\Auth\MeController::process
  methods: [ GET ]

# -------------------- Fin User  ---------------------------------------------------------------------------------------
