app_login:
  path: /login
  controller: App\Controller\Security\LoginController::login
  methods: [GET, POST]

app_register:
  path: /register
  controller: App\Controller\Security\RegistrationController::registration
  methods: [GET, POST]

app_logout:
  path: /logout
  methods: [GET]

ask_reset_password:
  path: /reset-password
  controller: App\Controller\Security\AskResetPasswordController:askResetPassword
  methods: [GET, POST]

reset_password:
  path: /reset-password/{passwordToken}
  controller: App\Controller\Security\ResetPasswordController:resetPassword
  methods: [GET, POST]

app_first_login:
  path: /first-login
  controller: App\Controller\Security\FirstLoginController::firstLogin
  methods: [GET, POST]


# -------------------- User  -------------------------------------------------------------------------------------------
api_user:
  path: api/v1/{locale}/me
  controller: App\Controller\Auth\MeController::process
  methods: [ GET ]

# -------------------- Fin User  ---------------------------------------------------------------------------------------


# -------------------- Référentiels ------------------------------------------------------------------------------------
api_referentiel:
  path: api/v1/{locale}/references
  controller: App\Controller\Reference\ListController::process
  methods: [ GET ]

api_referentiel_module:
  path: api/v1/{locale}/references/{module}
  controller: App\Controller\Reference\ListController::process
  methods: [ GET ]

api_referentiel_city:
  path: api/v1/{locale}/cities/{start}
  controller: App\Controller\Reference\CityController::process
  methods: [ GET ]

api_referentiel_country:
  path: api/v1/{locale}/countries/{start}
  controller: App\Controller\Reference\CountryController::process
  methods: [ GET ]
# -------------------- Fin Référentiels --------------------------------------------------------------------------------


# -------------------- Partenaires -------------------------------------------------------------------------------------
app_extract_partner:
  path: api/v1/{locale}/partners/extract
  controller: App\Controller\Partner\ExtractPartnerController::execute
  methods: [GET]

app_create_partner:
  path: api/v1/{locale}/partners
  controller: App\Controller\Partner\CreatePartnerController::process
  methods: [POST]

app_update_partner:
  path: api/v1/{locale}/partners/{partnerId}
  controller: App\Controller\Partner\UpdatePartnerController::updatePartner
  methods: [ PUT ]

app_get_partner:
  path: api/v1/{locale}/partners/{partnerId}
  controller: App\Controller\Partner\GetPartnerController::execute
  methods: [ GET ]

app_get_files_partner:
  path: api/v1/{locale}/partners/{partnerId}/files
  controller: App\Controller\Partner\GetFilesController::execute
  methods: [ GET ]

app_get_file_partner:
  path: api/v1/{locale}/partners/{partnerId}/files/{fileId}
  controller: App\Controller\Partner\GetFileController::execute
  methods: [ GET ]

app_post_file_partner:
  path: api/v1/{locale}/partners/{partnerId}/files
  controller: App\Controller\Partner\PostFileController::execute
  methods: [ POST ]

app_list_partner:
  path: api/v1/{locale}/partners
  controller: App\Controller\Partner\ListPartnerController::listPartner
  methods: [GET]
# -------------------- Fin Partenaires ---------------------------------------------------------------------------------



##  ------------ Produit -----------------------------------------------------------------------------------------------
app_extract_product:
  path: api/v1/{locale}/products/extract
  controller: App\Controller\Product\ExtractController::execute
  methods: [GET]

api_product_referentiel:
  path: api/v1/{locale}/products/reference
  controller: App\Controller\Product\ReferenceController::process
  methods: [ GET ]

app_list_product:
  path: api/v1/{locale}/products
  controller: App\Controller\Product\ListController::process
  methods: [GET]

app_all_product:
  path: api/v1/{locale}/all-products
  controller: App\Controller\Product\GetReferentielAllController::process
  methods: [GET]

app_create_product:
  path: api/v1/{locale}/product
  controller: App\Controller\Product\CreateController::process
  methods: [POST]

app_update_product:
  path: api/v1/{locale}/product/{productId}
  controller: App\Controller\Product\UpdateController::process
  methods: [ PUT ]

app_get_product:
  path: api/v1/{locale}/product/{productId}
  controller: App\Controller\Product\GetController::process
  methods: [ GET ]

app_get_files_product:
  path: api/v1/{locale}/products/{productId}/files
  controller: App\Controller\Product\GetFilesController::process
  methods: [ GET ]

app_get_file_product:
  path: api/v1/{locale}/products/{productId}/files/{fileId}
  controller: App\Controller\Product\GetFileController::process
  methods: [ GET ]

app_post_file_product:
  path: api/v1/{locale}/products/{productId}/files
  controller: App\Controller\Product\PostFileController::process
  methods: [ POST ]

##  ------------ End Produit -------------------------------------------------------------------------------------------



##  ------------ Prospect ----------------------------------------------------------------------------------------------
app_extract_prospect:
  path: api/v1/{locale}/prospects/extract
  controller: App\Controller\Prospect\ExtractController::execute
  methods: [GET]

app_list_prospect:
  path: api/v1/{locale}/prospects
  controller: App\Controller\Prospect\ListController::process
  methods: [GET]

app_create_prospect:
  path: api/v1/{locale}/prospect
  controller: App\Controller\Prospect\CreateController::process
  methods: [POST]

app_update_prospect:
  path: api/v1/{locale}/prospect/{prospectId}
  controller: App\Controller\Prospect\UpdateController::process
  methods: [ PUT ]

app_get_prospect:
  path: api/v1/{locale}/prospect/{prospectId}
  controller: App\Controller\Prospect\GetController::process
  methods: [ GET ]
##  ------------ End Prospect ------------------------------------------------------------------------------------------

##  ------------ Customer ------------------------------------------------------------------------------------------
app_extract_customer:
  path: api/v1/{locale}/customers/extract
  controller: App\Controller\Customer\ExtractController::process
  methods: [ GET ]

app_get_customer:
  path: api/v1/{locale}/customers/{customerId}
  controller: App\Controller\Customer\GetController::process
  methods: [ GET ]

app_list_customer:
  path: api/v1/{locale}/customers
  controller: App\Controller\Customer\ListController::process
  methods: [ GET ]

app_update_customer:
  path: api/v1/{locale}/customers/{customerId}
  controller: App\Controller\Customer\UpdateController::process
  methods: [ PUT ]
##  ------------ End Customer ------------------------------------------------------------------------------------------

##  ------------ Person ------------------------------------------------------------------------------------------------
app_list_person:
  path: api/v1/{locale}/persons
  controller: App\Controller\Person\ListController::process
  methods: [GET]
##  ------------ EndPerson ---------------------------------------------------------------------------------------------


##  ------------ Wallet ----------------------------------------------------------------------------------------------
## ****** Transaction *****************
app_wallet_transactions_extract:
  path: api/v1/{locale}/wallet/transactions/extract
  controller: App\Controller\Wallet\Transaction\ExtractController::execute
  methods: [GET]

app_wallet_transactions_list:
  path: api/v1/{locale}/wallet/transactions
  controller: App\Controller\Wallet\Transaction\ListController::process
  methods: [GET]

app_wallet_transaction_add_tag:
  path: api/v1/{locale}/wallet/transactions/{transactionId}/tags
  controller: App\Controller\Wallet\Transaction\AddTagController::process
  methods: [POST]

app_wallet_transaction_remove_tag:
  path: api/v1/{locale}/wallet/transactions/{transactionId}/tags
  controller: App\Controller\Wallet\Transaction\RemoveTagController::process
  methods: [DELETE]
## ****** Fin Transaction *****************

## ****** Souscription *****************
app_wallet_subscriptions_extract:
  path: api/v1/{locale}/wallet/transaction/subscriptions/extract
  controller: App\Controller\Wallet\Subscription\ExtractController::execute
  methods: [GET]
app_wallet_subscriptions_list:
  path: api/v1/{locale}/wallet/transaction/subscriptions
  controller: App\Controller\Wallet\Subscription\ListController::process
  methods: [GET]
app_wallet_subscriptions_create:
  path: api/v1/{locale}/wallet/transaction/subscriptions
  controller: App\Controller\Wallet\Subscription\CreateController::process
  methods: [POST]
app_wallet_subscriptions_detail:
  path: api/v1/{locale}/wallet/transaction/subscriptions/{transactionId}
  controller: App\Controller\Wallet\Subscription\GetController::process
  methods: [GET]
app_wallet_subscriptions_update:
  path: api/v1/{locale}/wallet/transaction/subscriptions/{transactionId}
  controller: App\Controller\Wallet\Subscription\UpdateController::process
  methods: [PUT]

app_wallet_subscriptions_actions:
    path: api/v1/{locale}/wallet/transaction/subscriptions/{transactionId}/actions
    controller: App\Controller\Wallet\Subscription\ActionsController::process
app_wallet_subscriptions_action:
  path: api/v1/{locale}/wallet/transaction/subscriptions/action/{transactionId}/{action}
  controller: App\Controller\Wallet\Subscription\ActionController::process
  methods: [PUT]
  requirements:
    action: engage|verify|confirm|validate|cancel
## ****** Fin Souscription *****************

## ****** Retrait Rachat *****************
app_wallet_withdrawals_list:
  path: api/v1/{locale}/wallet/transaction/withdrawals
  controller: App\Controller\Wallet\Withdrawal\ListController::process
  methods: [GET]
app_wallet_withdrawals_create:
  path: api/v1/{locale}/wallet/transaction/withdrawals
  controller: App\Controller\Wallet\Withdrawal\CreateController::process
  methods: [POST]
app_wallet_withdrawals_detail:
  path: api/v1/{locale}/wallet/transaction/withdrawals/{transactionId}
  controller: App\Controller\Wallet\Withdrawal\GetController::process
  methods: [GET]
app_wallet_withdrawals_update:
  path: api/v1/{locale}/wallet/transaction/withdrawals/{transactionId}
  controller: App\Controller\Wallet\Withdrawal\UpdateController::process
  methods: [PUT]

app_wallet_withdrawals_actions:
  path: api/v1/{locale}/wallet/transaction/withdrawals/{transactionId}/actions
  controller: App\Controller\Wallet\Withdrawal\ActionsController::process
app_wallet_withdrawals_action:
  path: api/v1/{locale}/wallet/transaction/withdrawals/action/{transactionId}/{action}
  controller: App\Controller\Wallet\Withdrawal\ActionController::process
  methods: [PUT]
  requirements:
    action: engage|verify|confirm|validate|cancel
## ****** Fin Retrait Rachat *****************


## ****** Gré à gré *****************
app_wallet_agreements_list:
  path: api/v1/{locale}/wallet/transaction/agreements
  controller: App\Controller\Wallet\Agreement\ListController::process
  methods: [GET]
app_wallet_agreements_create:
  path: api/v1/{locale}/wallet/transaction/agreements
  controller: App\Controller\Wallet\Agreement\CreateController::process
  methods: [POST]
app_wallet_agreements_detail:
  path: api/v1/{locale}/wallet/transaction/agreements/{transactionId}
  controller: App\Controller\Wallet\Agreement\GetController::process
  methods: [GET]
app_wallet_agreements_update:
  path: api/v1/{locale}/wallet/transaction/agreements/{transactionId}
  controller: App\Controller\Wallet\Agreement\UpdateController::process
  methods: [PUT]

app_wallet_agreements_actions:
  path: api/v1/{locale}/wallet/transaction/agreements/{transactionId}/actions
  controller: App\Controller\Wallet\Agreement\ActionsController::process
app_wallet_agreements_action:
  path: api/v1/{locale}/wallet/transaction/agreements/action/{transactionId}/{action}
  controller: App\Controller\Wallet\Agreement\ActionController::process
  methods: [PUT]
  requirements:
    action: engage|verify|confirm|validate|cancel
## ****** Fin Gré à gré *****************

## ****** Mutation *****************
app_wallet_mutations_list:
  path: api/v1/{locale}/wallet/transaction/mutations
  controller: App\Controller\Wallet\Mutation\ListController::process
  methods: [GET]
app_wallet_mutations_create:
  path: api/v1/{locale}/wallet/transaction/mutations
  controller: App\Controller\Wallet\Mutation\CreateController::process
  methods: [POST]
app_wallet_mutations_detail:
  path: api/v1/{locale}/wallet/transaction/mutations/{transactionId}
  controller: App\Controller\Wallet\Mutation\GetController::process
  methods: [GET]
app_wallet_mutations_update:
  path: api/v1/{locale}/wallet/transaction/mutations/{transactionId}
  controller: App\Controller\Wallet\Mutation\UpdateController::process
  methods: [PUT]

app_wallet_mutations_actions:
  path: api/v1/{locale}/wallet/transaction/mutations/{transactionId}/actions
  controller: App\Controller\Wallet\Mutation\ActionsController::process
app_wallet_mutations_action:
  path: api/v1/{locale}/wallet/transaction/mutations/action/{transactionId}/{action}
  controller: App\Controller\Wallet\Mutation\ActionController::process
  methods: [PUT]
  requirements:
    action: engage|verify|confirm|validate|cancel
## ****** Fin Mutation *****************

##  ------------ End Wallet ------------------------------------------------------------------------------------------
## ****** Investor *****************
app_investor_get_slices:
  path: api/v1/{locale}/investors/{investorId}/slices
  controller: App\Controller\Investor\GetSlicesController::process
  methods: [GET]
## ****** Fin Investor *****************
